backend:
  name: github
  repo: NoahHaile/Personal-Blog  # Replace with your actual GitHub repo
  branch: main
  auth_scope: repo

media_folder: "static/uploads"  # Where images are stored
public_folder: "/uploads"

collections:
  - name: "articles"
    label: "Blog Posts"
    folder: "content/articles"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
